require:
  - standard
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
